import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="flex gap-4 py-1 px-2 flex-wrap">
          <Link href="/">Home</Link>
          <div className="flex-1" />
          <Link href="/info">Info</Link>
          <Link href="/counter">Counter</Link>
          <Link href="/converter">Converter</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
